name: 'github actions build and deploy gh-pages'
on: 
  push:
    branches:
      - feature-gitbook
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: install and build
          run: |
            npm install -g
            gitbook build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
          with: 
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BRANCH: gh-pages
            FOLDER: _book
